# Generated by Django 4.0.6 on 2022-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_author_reviews_author_reviews_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
