# Generated by Django 4.0.6 on 2022-08-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_reviews_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product',
            new_name='article',
        ),
    ]
