# Generated by Django 4.0.6 on 2022-08-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_product_reviews_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='article',
            new_name='product',
        ),
    ]
